// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlfudwbvbyryynvtnaic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZnVkd2J2YnlyeXludnRuYWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NDA3NjMsImV4cCI6MjA5OTUxNjc2M30.L7xUhCVT0FXkCZGU9jAGeGyzvdgyCCDxGNoDEO2klm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});